name: Yes We Jekyll
pygments: true
title: 'Yes We Jekyll'
exclude: ['LICENSE', 'README.md', 'Rakefile', 'component.json']
description: 'Yes We Jekyll! Développer et héberger votre propre site web statique ou blog est vraiment facile. Dans ce guide, je vous présenterai comment utiliser le framework très populaire de Jekyll. Utilisé durant la campagne Obma, ça ne doit pas être trop mauvais.'
